title: About Me
url: https://k4ni5h.github.io/
description: An IIT grad, a Software Developer, and a Tech Enthusiast; passionate about IoTs, BlockChain, ChatBots, Genetic Algorithms, Natural Language Processing, Computer Vision, etc. I always excited about making things more generic, dynamic, and reusable.
github_url: https://github.com/k4ni5h/
markdown: kramdown
